import { NextRequest, NextResponse } from "next/server";
import { interviewGraph } from "@/lib/agents/graph";
import { HumanMessage } from "@langchain/core/messages";

export async function POST(req: NextRequest) {
    try {
        const { message, candidateCode, previousMessages = [] } = await req.json();

        // Reconstruct the message history for LangChain
        const formattedMessages = previousMessages.map((msg: any) =>
            msg.role === "user" ? new HumanMessage(msg.content) : new HumanMessage(msg.content) // Simplified for initial build
        );
        formattedMessages.push(new HumanMessage(message));

        // Run the LangGraph state machine
        const result = await interviewGraph.invoke({
            messages: formattedMessages,
            candidateCode: candidateCode || "",
        });

        // The result contains the updated state. We grab the last message generated by the Interviewer.
        const lastMessage = result.messages[result.messages.length - 1];

        return NextResponse.json({
            response: lastMessage.content,
        });

    } catch (error) {
        console.error("Interview API Error:", error);
        return NextResponse.json({ error: "Failed to process interview response" }, { status: 500 });
    }
}